name = "conversion-kv-api"
type = "javascript"

[[kv_namespaces]]
binding = "conversion_workers_experiments"
id = "2b8992cf7f1b439ba8fc4c6bf0f8b261"  # ðŸ‘ˆ from your screenshot

[env.production]
kv_namespaces = [
  { binding = "conversion_workers_experiments", id = "2b8992cf7f1b439ba8fc4c6bf0f8b261" }
]
