name = "conversion-kv-api"
type = "javascript"

[[kv_namespaces]]
binding = "EXPERIMENTS"
id = "2b8992cf7f1b439baf8c4c6bf0f8b261"  # ðŸ‘ˆ from your screenshot

[env.production]
kv_namespaces = [
  { binding = "EXPERIMENTS", id = "2b8992cf7f1b439baf8c4c6bf0f8b261" }
]
